#ifndef CONSTANTES_H
#define CONSTANTES_H

// Físicas
#define GRAVEDAD -0.05f
#define FUERZA_SALTO 4.5f
#define VELOCIDAD_TERMINAL -2.5f
#define PASO_VERTICAL 0.01f

// Dimensiones del mapa y niveles
#define MAX_BLOQUES 3000
#define FLOORS_PER_LEVEL 16
#define FLOOR_HEIGHT 1
#define PRE_FLOOR_HEIGHT 1
#define ROWS_BETWEEN_FLOORS 4
#define TOTAL_FLOOR_HEIGHT (FLOOR_HEIGHT + PRE_FLOOR_HEIGHT)
#define TOTAL_ROWS_FOR_FLOORS ((FLOORS_PER_LEVEL - 1) * TOTAL_FLOOR_HEIGHT)
#define TOTAL_ROWS_BETWEEN_FLOORS ((FLOORS_PER_LEVEL - 1) * ROWS_BETWEEN_FLOORS)
#define TOTAL_ROWS (1 + TOTAL_ROWS_FOR_FLOORS + TOTAL_ROWS_BETWEEN_FLOORS)

// Otros
#define PORT 8080
#define BUFFER_SIZE 1024
#define MAX_CLIENTS 6
#define MAX_FRUTAS 4


#endif
